config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'mode' => 'cop#mode_options'
  post 'mode' => 'cop#set_mode'

  resources :tasks

  resources :points do
    resources :bmessages
    resources :gmessages
  end

  root 'welcome#index'

end

app/models/bmessage.rb
class Bmessage < ActiveRecord::Base
  belongs_to :point
end

app/models/gmessage.rb
class Gmessage < ActiveRecord::Base
  belongs_to :point
end

app/models/point.rb
class Point < ActiveRecord::Base
  has_one :gmessage
  has_one :bmessage
  accepts_nested_attributes_for :gmessage
  accepts_nested_attributes_for :bmessage

  validates :statpoint, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base

  validates :name, :due_by, :est_time, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bmessage_controller.rb
class BmessagesController < ApplicationController
  before_action :set_point

  def index
    @bmessages = Bmessage.all
  end

  def show
    @bmessage.find(params[:id])
  end

  def new
    @bmessage = Bmessage.new
  end

  def edit
  end

  def create
    @bmessage = Bmessage.new(bmessage_params)
    @bmessage.point = Point.find(params[:point_id])

    if @bmessage.save
     redirect_to @bmessage, notice: 'message was successfully created.'
    else
      render :new
    end
  end

  def update
    if @bmessage.update_attributes(bmessage_params)
      redirect_to bmessage_path(@bmessage), notice: 'message successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    bmessage.find(params[:id]).destroy
    redirect_to bmessages_path, notice: 'message successfully deleted.'
  end

  private
    def set_point
      @point = Point.find(params[:point_id])
    end

    def bmessage_params
      params.require(:bmessage).permit(:body, :photo_url)
    end
end

app/controllers/cop_controller.rb
class CopController < ApplicationController
  def mode_options
  end

  def set_mode
    if params[:name] == 'good'
      current_user.update_attributes(good_cop?: true)
    elsif params[:name] == 'bad'
       current_user.update_attributes(good_cop?: false)
    end

    redirect_to tasks_path
  end

end

app/controllers/gmessage_controller.rb
class GmessagesController < ApplicationController
  before_action :set_point

  def index
    @gmessages = Gmessage.all
  end

  def show
    @gmessage.find(params[:id])
  end

  def new
    @gmessage = Gmessage.new
  end

  def edit
  end

  def create
    @gmessage = Gmessage.new(gmessage_params)
    @gmessage.point = Point.find(params[:point_id])

    if @gmessage.save
     redirect_to @gmessage, notice: 'message was successfully created.'
    else
      render :new
    end
  end

  def update
    if @gmessage.update_attributes(gmessage_params)
      redirect_to gmessage_path(@gmessage), notice: 'message successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    gmessage.find(params[:id]).destroy
    redirect_to gmessages_path, notice: 'message successfully deleted.'
  end

  private
    def set_point
      @point = Point.find(params[:point_id])
    end

    def gmessage_params
      params.require(:gmessage).permit(:body, :photo_url)
    end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :set_point, only: [:show, :edit, :update, :destroy]
  def index
    @points = Point.all
  end

  def show
  end

  def new
    @point = Point.new
  end

  def create
    @point = Point.new(point_params)

    if @point.save
      flash[:success] = 'point successfully created.'
      redirect_to @point
    else
      redirect_to root_path
    end
  end

  def edit
  end

  def update
    if @point.update_attributes(point_params)
      flash[:success] = 'point successfully updated.'
      redirect_to point_path(@point)
    else
      render :edit
    end
  end

  def destroy
    @point = @task.points.find(params[:id])
    @point.destroy
    flash[:success] = 'point successfully deleted.'
    redirect_to task_points_path
  end

private
  def set_point
    @point = Point.find(params[:id])
  end

  def point_params
    params.require(:point).permit(:statpoint)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)

    if @task.save
     redirect_to @task, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    if @task.update_attributes(task_params)
      redirect_to task_path(@task), notice: 'Task successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    Task.find(params[:id]).destroy
    redirect_to tasks_path, notice: 'Task successfully deleted.'
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:name, :due_by, :est_time, :status)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base
  def index
    render template: "layouts/welcome"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/point_helper.rb
module PointHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/views/bmessages/_form.html.erb
<%= form_for [@bmessage] do |f| %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bmessages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>
    <% @bmessages.each do |message| %>
      <%= message.body %>
    <% end %>
</h1>

app/views/bmessages/new.html.erb
<h1>Create a new Message</h1>
<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/bmessages/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
<%= @bmessage.body %>
</h1>
<%= image_tag@bmessage.photo_url %>

<h1>Made any progress yet?</h1>
<%= link_to 'Update your status', points_path %>

app/views/cop/mode_options.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
      <div class="container">
        <h1>
          Choose a Mode:
        </h1>
      </div>
    </div>
    <br><br><br><br>

<%= button_to 'I need some inspiration', {}, {action: 'set_mode', class: 'btn btn-info btn-lg', name: 'good'} %>
<br>
<%= button_to 'I need some tough love', {}, {action: 'set_mode', class: 'btn btn-info btn-lg', name: 'bad'} %>

app/views/gmessages/_form.html.erb
<%= form_for [@gmessage] do |f| %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gmessages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>
    <% @gmessage.each do |message| %>
      <%= message.body %>
    <% end %>
</h1>

app/views/gmessages/new.html.erb
<h1>Create a new Message</h1>
<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/gmessages/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
<%= @gmessage.body %>
</h1>
<%= image_tag@gmessage.photo_url %>

<h1>Made any progress yet?</h1>
<%= link_to 'Update your status', points_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <%= google_webfonts_init({
    google: ['Quicksand']}) %>

    <title>Motivation App</title>
    <link href='http://fonts.googleapis.com/css?family=Quicksand:300,400' rel='stylesheet' type='text/css'>

  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" rel="home" href="#" title="Motivator">
          <img style="max-width:100px; margin-top: -7px;" src="http://i.imgur.com/C1uoXSZ.jpg"></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="/tasks">Tasks</a></li>
            <li class="right"><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>

            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Sign In", new_user_session_path  %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
    <div class="starter-template">
      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= stylesheet_link_tag    'welcome', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'welcome', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <%= google_webfonts_init({
    google: ['Quicksand']}) %>

    <title>Motivator</title>
    <link href='http://fonts.googleapis.com/css?family=Quicksand:300,400' rel='stylesheet' type='text/css'>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">

    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Motivator</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li class="active"><a href="#">Home</a></li>
                  <li><a href="/tasks">Tasks</a></li>
                  <li><%= link_to "Sign Up", new_user_registration_path %></li>
                  <li><%= link_to "Sign In", new_user_session_path  %></li>
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            <img class='smallerimg' src="http://i.imgur.com/1swOI86.png">
            <h1 class="cover-heading">Motivate Yourself</h1>
            <p class="lead">Motivator is a simple app that helps you avoid procrastination and get your important tasks done.</p>
          </div>


          <div class="mastfoot">
            <div class="inner">
            <p class="lead">
              <a href="/mode" class="btn btn-lg btn-default">Motivate Me!</a>
            </p>
              <p>A <a href="http://generalassemb.ly">WDI </a>project by by <a href="https://twitter.com/katyfeng">Katy Feng</a></p>
            </div>
          </div>

        </div>

      </div>

    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/docs.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for [@message] do |f| %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>
    <% @messages.each do |message| %>
      <%= message.body %>
    <% end %>
</h1>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
<%= @message.body %>
</h1>
<%= image_tag@message.photo_url %>

<h1>Made any progress yet?</h1>
<%= link_to 'Update your status', points_path %>

app/views/points/_form.html.erb
<%= form_for [@task, @point] do |f| %>

  <div class="field">
    <%= f.label :statpoint %><br>
    <%= f.text_field :statpoint %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/points/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

<%= button_to 'Delete', @task, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Show', task_points_path(@task.id) %> |
<%= link_to 'Back', tasks_path %>

app/views/points/index.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
      <div class="container">
        <h1>Progress</h1>
        <p>What's the status of your task?</p>
      </div>
    </div>
<div>
<br><br>
<img class = 'gif' src = 'http://media.giphy.com/media/lXiRtipU3IhXitYVG/giphy.gif'>
</div>

<p class="lg">
  <% @points.each do |point| %>
    <% point.statpoint %>
    <%= link_to point.statpoint, point, class: "black" %>%
  <% end %>
</p>



<br>
<br>
<div class="btn btn-info">
<%= link_to 'Back', :back %>
</div>

app/views/points/new.html.erb
<h1>Create a new Status</h1>
<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/points/show.html.erb
<p id="notice"><%= notice %></p>

<p class="md">You are <%= @point.statpoint %>% done...</p>
<div>
<% if current_user.good_cop? == true %>
     <h1><%= @point.gmessage.body %></h1><br>
     <img src='<%= @point.gmessage.photo_url %>'>
<% else %>
     <h1><%= @point.bmessage.body %></h1><br>
     <img src='<%= @point.bmessage.photo_url %>'>
<% end %>
</div>
<br><br><br>
<div class="btn btn-info">
<%= link_to 'Made some progress?', points_path%>
</div>

<div class="btn btn-success">
<a href="http://selfcontrolapp.com/" target="_blank">Help! I'm Hopeless</a>
</div>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :due_by %><br>
    <%= f.text_field :due_by %>
  </div>

  <div class="field">
    <%= f.label :est_time %><br>
    <%= f.text_field :est_time %>
  </div>
<br>

    <%= f.submit %>

<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render 'form' %>

<%= button_to 'Delete', @task, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
      <div class="container">
        <h1>Your Tasks</h1>
        <p>View your current tasks and create new ones.</p>
      </div>
    </div>
<br>
<br>
<br>
<tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><h2><%= link_to task.name, task, class: "black" %></h2></td>
        <td><%= link_to 'Edit', edit_task_path(task), class: "black" %> | <%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "black" %></td><br><br>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="btn btn-info">
<%= link_to 'Add a New Task', new_task_path %>
</div>

app/views/tasks/new.html.erb
<div class="jumbotron">
      <div class="container">
          <h1>Create a new Task</h1>
      </div>
    </div>
<br><br>
<br>
<%= render 'form' %>
<br>
<div class="btn btn-info">
<%= link_to 'Back', tasks_path %>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
      <div class="container">
        <h1>
          <%= @task.name %>
        </h1>
      </div>
    </div>
    <br><br><br>

<h1> You have <%= Time.diff(Chronic.parse(@task.due_by), Chronic.parse('today'), '%d and %h:%m')[:diff] %> left to complete: </h1>

<br>

<p> Due By:
<%= @task.due_by %>
</p>
<p> Estimated time:
<%= @task.est_time %>
</p>


<%= link_to 'Edit', edit_task_path(@task), class: "black" %> |
<%= link_to 'Back', tasks_path, class: "black" %>
<br><br><br>
<div class="btn btn-info">
<%= link_to 'How far along are you?', points_path%>
</div>